"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Folder_1 = require("./Folder");
const DataFile_1 = require("./DataFile");
const FileSystem_1 = require("./FileSystem");
const SnapshotStorage_1 = require("./SnapshotStorage");
let fs = new FileSystem_1.default("C");
let pictures = fs.root_folder.addFolder(new Folder_1.default("pictures"));
let photo = pictures.addFolder(new Folder_1.default("Photo"));
let november = photo.addFolder(new Folder_1.default("november"));
let first_jpeg = november.addDataFile(new DataFile_1.default("1.jpeg"));
let second_jpeg = november.addDataFile(new DataFile_1.default("2.jpeg"));
let december = photo.addFolder(new Folder_1.default("december"));
let new_year_jpeg = december.addDataFile(new DataFile_1.default("new_year.jpeg"));
let GIF = pictures.addFolder(new Folder_1.default("GIF"));
let movies = fs.root_folder.addFolder(new Folder_1.default("movies"));
let film_avi = movies.addDataFile(new DataFile_1.default("film.avi"));
let system = fs.root_folder.addFolder(new Folder_1.default("system"));
let program_exe = system.addDataFile(new DataFile_1.default("system.exe"));
let root_file_init = fs.root_folder.addDataFile(new DataFile_1.default("root_file.init"));
fs.printComposition();
console.log("\n==========================\n");
SnapshotStorage_1.default.addSnapshot(fs.createMemento());
fs = new FileSystem_1.default("D");
let readme_file = fs.root_folder.addDataFile(new DataFile_1.default("read.me"));
fs.printComposition();
console.log("fs после перезаписи\n================\n");
fs.restoreMemento(SnapshotStorage_1.default.getLastSnapshot());
fs.printComposition();
console.log("fs после восстановления из снапа");
//# sourceMappingURL=main.js.map